export const NEW_REPORT_TITLE = 'New report';

export function buildDefaultReportName(
  dateFrom: string,
  dateTo: string,
): string {
  return `Report for ${dateFrom} • ${dateTo}`;
}

export function isAutoGeneratedReportName(
  name: string,
  previousDateFrom?: string,
  previousDateTo?: string,
): boolean {
  const trimmed = name.trim();

  if (trimmed === NEW_REPORT_TITLE) {
    return true;
  }

  if (previousDateFrom && previousDateTo) {
    return trimmed === buildDefaultReportName(previousDateFrom, previousDateTo);
  }

  return false;
}
