import { formatReportMonth } from '@/lib/reports/report-month';

export const NEW_REPORT_TITLE = 'New report';

export function buildDefaultReportName(
  dateFrom: string,
  dateTo: string,
): string {
  void dateTo;
  return `Report for ${formatReportMonth(dateFrom)}`;
}

export function isAutoGeneratedReportName(
  name: string,
  previousDateFrom?: string,
  previousDateTo?: string,
): boolean {
  const trimmed = name.trim();

  if (trimmed === NEW_REPORT_TITLE) {
    return true;
  }

  if (previousDateFrom && previousDateTo) {
    return trimmed === buildDefaultReportName(previousDateFrom, previousDateTo);
  }

  return false;
}
