'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMemo, useRef, useState, useTransition } from 'react';

import { MonthReportCategoryTotalsTable } from '@/app/(protected)/report/new/components/month-report-category-totals-table';
import { MonthReportSummaryTable } from '@/app/(protected)/reports/components/month-report-summary-table';
import {
  createReport,
  updateReport,
} from '@/app/(protected)/reports/actions/report-actions';
import { ReportTitleInput } from '@/app/(protected)/reports/components/report-title-input';
import { SaveReportDialog } from '@/app/(protected)/reports/components/save-report-dialog';
import { Button } from '@/components/ui/button';
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle,
} from '@/components/ui/empty';
import { MonthPicker } from '@/components/ui/month-picker';
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel,
} from '@/components/ui/field';
import {
  buildDefaultReportName,
  isAutoGeneratedReportName,
  NEW_REPORT_TITLE,
} from '@/lib/reports/build-default-report-name';
import type { MonthReportCategoryTotal } from '@/lib/reports/get-month-report-category-totals';
import {
  groupMonthReportCategoryTotals,
  hasMonthReportCategoryTotals,
  monthReportCategoryTableTypes,
} from '@/lib/reports/group-month-report-category-totals';
import { buildMonthReportSearchParams } from '@/lib/reports/month-report-search-params';
import type { MonthReportSearchParams } from '@/lib/reports/month-report-search-params';
import type { SpendingCategoryAverage } from '@/lib/reports/get-spending-category-month-averages';
import { formatReportMonth } from '@/lib/reports/report-month';
import { sumCategoryTotals } from '@/lib/reports/sum-category-totals';
import type { ReportRow } from '@/lib/reports/get-report-by-id';
import {
  REPORT_MONTH_REQUIRED_MESSAGE,
  validateReportDateRange,
} from '@/lib/reports/validate-report-date-range';
import { validateReportName } from '@/lib/reports/validate-report-name';

import type { CategoryColorToken } from '@/lib/categories/category-colors';
import type { CategoryIconName } from '@/lib/categories/category-icons';

type CategoryOption = {
  id: string;
  name: string;
  color: CategoryColorToken;
  icon: CategoryIconName;
};

type MonthReportViewProps = {
  mode: 'new' | 'edit';
  reportId?: string;
  savedReport?: ReportRow;
  listParams: MonthReportSearchParams;
  initialTitle: string;
  validationError?: string;
  categoryTotals?: MonthReportCategoryTotal[];
  spendingCategoryAverages?: Record<string, SpendingCategoryAverage>;
  primaryAccountBalanceBeforeIncome?: string | null;
  categories?: CategoryOption[];
};

function getInitialTitle(
  mode: MonthReportViewProps['mode'],
  listParams: MonthReportSearchParams,
  initialTitle: string,
): string {
  if (mode !== 'new') {
    return initialTitle;
  }

  const validation = validateReportDateRange(
    listParams.dateFrom,
    listParams.dateTo,
  );

  if (validation.ok) {
    return buildDefaultReportName(validation.dateFrom, validation.dateTo);
  }

  return NEW_REPORT_TITLE;
}

export function MonthReportView({
  mode,
  reportId,
  savedReport,
  listParams,
  initialTitle,
  validationError: serverValidationError,
  categoryTotals,
  spendingCategoryAverages = {},
  primaryAccountBalanceBeforeIncome = null,
  categories = [],
}: MonthReportViewProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [dateFrom, setDateFrom] = useState(listParams.dateFrom);
  const [dateTo, setDateTo] = useState(listParams.dateTo);
  const [title, setTitle] = useState(() =>
    getInitialTitle(mode, listParams, initialTitle),
  );
  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saveSuccess, setSaveSuccess] = useState<string | null>(null);
  const lastAutoTitleDatesRef = useRef({
    dateFrom: listParams.dateFrom,
    dateTo: listParams.dateTo,
  });

  const pickerValidation = validateReportDateRange(dateFrom, dateTo);
  const showRequiredMonthDescription =
    !pickerValidation.ok &&
    pickerValidation.message === REPORT_MONTH_REQUIRED_MESSAGE;
  const pickerRangeError =
    !pickerValidation.ok && !showRequiredMonthDescription
      ? pickerValidation.message
      : null;

  const showDashboard = categoryTotals !== undefined;
  const groupedTotals = useMemo(
    () =>
      categoryTotals
        ? groupMonthReportCategoryTotals(categoryTotals)
        : null,
    [categoryTotals],
  );
  const hasTotals =
    groupedTotals !== null && hasMonthReportCategoryTotals(groupedTotals);

  const summaryTotals = useMemo(() => {
    if (!groupedTotals) {
      return null;
    }

    return {
      totalIncome: sumCategoryTotals(groupedTotals.income),
      totalSpending: sumCategoryTotals(groupedTotals.spending),
    };
  }, [groupedTotals]);

  const resolvedDates = pickerValidation.ok ? pickerValidation : null;

  const isDirty = useMemo(() => {
    if (mode !== 'edit' || !savedReport) {
      return false;
    }

    if (validateReportName(title) !== null) {
      return false;
    }

    return (
      title.trim() !== savedReport.name ||
      dateFrom !== savedReport.dateFrom ||
      dateTo !== savedReport.dateTo
    );
  }, [mode, savedReport, title, dateFrom, dateTo]);

  const canSave =
    mode === 'new'
      ? showDashboard &&
        resolvedDates !== null &&
        validateReportName(title) === null
      : isDirty;

  const showSaveSuccess = saveSuccess !== null && !isDirty;

  function handleTitleChange(nextTitle: string) {
    setSaveSuccess(null);
    setTitle(nextTitle);
  }

  function handleMonthChange(nextFrom: string, nextTo: string) {
    setSaveSuccess(null);
    setDateFrom(nextFrom);
    setDateTo(nextTo);

    if (mode !== 'new') {
      return;
    }

    const validation = validateReportDateRange(nextFrom, nextTo);

    if (!validation.ok) {
      return;
    }

    setTitle((current) => {
      if (
        !isAutoGeneratedReportName(
          current,
          lastAutoTitleDatesRef.current.dateFrom,
          lastAutoTitleDatesRef.current.dateTo,
        )
      ) {
        return current;
      }

      return buildDefaultReportName(validation.dateFrom, validation.dateTo);
    });

    lastAutoTitleDatesRef.current = {
      dateFrom: validation.dateFrom,
      dateTo: validation.dateTo,
    };
  }

  function handleApplyDateRange() {
    if (!pickerValidation.ok) {
      return;
    }

    if (
      pickerValidation.dateFrom === listParams.dateFrom &&
      pickerValidation.dateTo === listParams.dateTo
    ) {
      return;
    }

    const query = buildMonthReportSearchParams({
      dateFrom: pickerValidation.dateFrom,
      dateTo: pickerValidation.dateTo,
    });

    startTransition(() => {
      if (mode === 'new') {
        router.replace(`/report/new${query}`);
        return;
      }

      if (reportId) {
        router.replace(`/reports/${reportId}${query}`);
      }
    });
  }

  function handleSaveConfirm() {
    if (!resolvedDates) {
      return;
    }

    const nameError = validateReportName(title);

    if (nameError) {
      setSaveError(nameError);
      return;
    }

    setSaveError(null);

    startTransition(async () => {
      const input = {
        name: title,
        dateFrom: resolvedDates.dateFrom,
        dateTo: resolvedDates.dateTo,
      };

      const result =
        mode === 'new'
          ? await createReport(input)
          : reportId
            ? await updateReport(reportId, input)
            : { ok: false as const, error: 'Report not found.' };

      if (!result.ok) {
        setSaveError(result.error);
        return;
      }

      setSaveDialogOpen(false);

      if (mode === 'new') {
        router.push('/reports');
        return;
      }

      setSaveSuccess('Report saved.');
      router.refresh();
    });
  }

  return (
    <div className="flex flex-col gap-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <ReportTitleInput
          value={title}
          onChange={handleTitleChange}
          disabled={isPending}
          className="min-w-[200px] flex-1"
        />
        <div className="flex shrink-0 flex-wrap items-center gap-2">
          <Button
            type="button"
            disabled={!canSave || isPending}
            onClick={() => {
              setSaveError(null);
              setSaveDialogOpen(true);
            }}
          >
            Save
          </Button>
          <Button type="button" variant="ghost" asChild>
            <Link href="/reports">Back to reports</Link>
          </Button>
        </div>
      </div>

      <Field
        className="w-full sm:w-auto"
        data-invalid={
          showRequiredMonthDescription ||
          pickerRangeError !== null ||
          serverValidationError
            ? true
            : undefined
        }
      >
        <FieldLabel htmlFor="report-month">Month</FieldLabel>
        <div className="flex flex-wrap items-center gap-3">
          <MonthPicker
            id="report-month"
            disableFuture
            value={{ dateFrom, dateTo }}
            aria-invalid={
              showRequiredMonthDescription ||
              pickerRangeError !== null ||
              !!serverValidationError
            }
            onValueChange={({ dateFrom: nextFrom, dateTo: nextTo }) => {
              handleMonthChange(nextFrom, nextTo);
            }}
          />
          <Button
            type="button"
            disabled={!pickerValidation.ok || isPending}
            onClick={handleApplyDateRange}
          >
            {isPending ? 'Applying…' : 'Apply'}
          </Button>
        </div>
        {showRequiredMonthDescription ? (
          <FieldDescription className="text-destructive">
            {REPORT_MONTH_REQUIRED_MESSAGE}
          </FieldDescription>
        ) : null}
        {pickerRangeError ? <FieldError>{pickerRangeError}</FieldError> : null}
        {serverValidationError ? (
          <FieldError>{serverValidationError}</FieldError>
        ) : null}
      </Field>

      {showSaveSuccess ? (
        <p className="text-sm text-muted-foreground" role="status">
          {saveSuccess}
        </p>
      ) : null}

      {showDashboard && groupedTotals ? (
        <>
          {hasTotals && summaryTotals ? (
            <MonthReportSummaryTable
              totalIncome={summaryTotals.totalIncome}
              totalSpending={summaryTotals.totalSpending}
              primaryAccountBalanceBeforeIncome={primaryAccountBalanceBeforeIncome}
            />
          ) : null}
          <section className="flex flex-col gap-6">
            <div>
              <h2 className="text-lg font-semibold">By category</h2>
              <p className="text-sm text-muted-foreground">
                Totals for {formatReportMonth(listParams.dateFrom)}
              </p>
            </div>
            {!hasTotals ? (
              <Empty className="border">
                <EmptyHeader>
                  <EmptyTitle>No transactions this month</EmptyTitle>
                  <EmptyDescription>
                    Try a different month.
                  </EmptyDescription>
                </EmptyHeader>
              </Empty>
            ) : (
              <>
                {monthReportCategoryTableTypes.map((tableType) => (
                  <MonthReportCategoryTotalsTable
                    key={tableType}
                    tableType={tableType}
                    data={groupedTotals[tableType]}
                    dateFrom={listParams.dateFrom}
                    dateTo={listParams.dateTo}
                    categories={categories}
                    spendingCategoryAverages={spendingCategoryAverages}
                  />
                ))}
              </>
            )}
          </section>
        </>
      ) : null}

      <SaveReportDialog
        open={saveDialogOpen}
        onOpenChange={setSaveDialogOpen}
        name={title.trim()}
        dateFrom={resolvedDates?.dateFrom ?? dateFrom}
        dateTo={resolvedDates?.dateTo ?? dateTo}
        isPending={isPending}
        error={saveError}
        onConfirm={handleSaveConfirm}
      />
    </div>
  );
}

export { NEW_REPORT_TITLE };
