'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useRef, useState, useTransition } from 'react';

import { MonthReportCategoryTotalsTable } from '@/app/(protected)/report/new/components/month-report-category-totals-table';
import {
  createReport,
  updateReport,
} from '@/app/(protected)/reports/actions/report-actions';
import { ReportTitleInput } from '@/app/(protected)/reports/components/report-title-input';
import { SaveReportDialog } from '@/app/(protected)/reports/components/save-report-dialog';
import { Button } from '@/components/ui/button';
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle,
} from '@/components/ui/empty';
import { DateRangePicker } from '@/components/ui/date-range-picker';
import { Field, FieldLabel } from '@/components/ui/field';
import {
  buildDefaultReportName,
  isAutoGeneratedReportName,
  NEW_REPORT_TITLE,
} from '@/lib/reports/build-default-report-name';
import type { MonthReportCategoryTotal } from '@/lib/reports/get-month-report-category-totals';
import {
  groupMonthReportCategoryTotals,
  hasMonthReportCategoryTotals,
  monthReportCategoryTableTypes,
} from '@/lib/reports/group-month-report-category-totals';
import { buildMonthReportSearchParams } from '@/lib/reports/month-report-search-params';
import type { MonthReportSearchParams } from '@/lib/reports/month-report-search-params';
import type { ReportRow } from '@/lib/reports/get-report-by-id';
import { validateReportDateRange } from '@/lib/reports/validate-report-date-range';
import { validateReportName } from '@/lib/reports/validate-report-name';

const DEBOUNCE_MS = 300;

type CategoryOption = {
  id: string;
  name: string;
};

type MonthReportViewProps = {
  mode: 'new' | 'edit';
  reportId?: string;
  savedReport?: ReportRow;
  listParams: MonthReportSearchParams;
  initialTitle: string;
  validationError?: string;
  categoryTotals?: MonthReportCategoryTotal[];
  categories?: CategoryOption[];
};

function getInitialTitle(
  mode: MonthReportViewProps['mode'],
  listParams: MonthReportSearchParams,
  initialTitle: string,
): string {
  if (mode !== 'new') {
    return initialTitle;
  }

  const validation = validateReportDateRange(
    listParams.dateFrom,
    listParams.dateTo,
  );

  if (validation.ok) {
    return buildDefaultReportName(validation.dateFrom, validation.dateTo);
  }

  return NEW_REPORT_TITLE;
}

export function MonthReportView({
  mode,
  reportId,
  savedReport,
  listParams,
  initialTitle,
  validationError: serverValidationError,
  categoryTotals,
  categories = [],
}: MonthReportViewProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [dateFrom, setDateFrom] = useState(listParams.dateFrom);
  const [dateTo, setDateTo] = useState(listParams.dateTo);
  const [title, setTitle] = useState(() =>
    getInitialTitle(mode, listParams, initialTitle),
  );
  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saveSuccess, setSaveSuccess] = useState<string | null>(null);
  const lastAutoTitleDatesRef = useRef({
    dateFrom: listParams.dateFrom,
    dateTo: listParams.dateTo,
  });

  const pickerValidation = validateReportDateRange(dateFrom, dateTo);
  const validationError = pickerValidation.ok
    ? serverValidationError
    : pickerValidation.message;

  const showDashboard = categoryTotals !== undefined;
  const groupedTotals = useMemo(
    () =>
      categoryTotals
        ? groupMonthReportCategoryTotals(categoryTotals)
        : null,
    [categoryTotals],
  );
  const hasTotals =
    groupedTotals !== null && hasMonthReportCategoryTotals(groupedTotals);

  const resolvedDates = pickerValidation.ok ? pickerValidation : null;

  const isDirty = useMemo(() => {
    if (mode !== 'edit' || !savedReport) {
      return false;
    }

    if (validateReportName(title) !== null) {
      return false;
    }

    return (
      title.trim() !== savedReport.name ||
      dateFrom !== savedReport.dateFrom ||
      dateTo !== savedReport.dateTo
    );
  }, [mode, savedReport, title, dateFrom, dateTo]);

  const canSave =
    mode === 'new'
      ? showDashboard &&
        resolvedDates !== null &&
        validateReportName(title) === null
      : isDirty;

  const showSaveSuccess = saveSuccess !== null && !isDirty;

  function handleTitleChange(nextTitle: string) {
    setSaveSuccess(null);
    setTitle(nextTitle);
  }

  function handleDateRangeChange(nextFrom: string, nextTo: string) {
    setSaveSuccess(null);
    setDateFrom(nextFrom);
    setDateTo(nextTo);

    if (mode !== 'new') {
      return;
    }

    const validation = validateReportDateRange(nextFrom, nextTo);

    if (!validation.ok) {
      return;
    }

    setTitle((current) => {
      if (
        !isAutoGeneratedReportName(
          current,
          lastAutoTitleDatesRef.current.dateFrom,
          lastAutoTitleDatesRef.current.dateTo,
        )
      ) {
        return current;
      }

      return buildDefaultReportName(validation.dateFrom, validation.dateTo);
    });

    lastAutoTitleDatesRef.current = {
      dateFrom: validation.dateFrom,
      dateTo: validation.dateTo,
    };
  }

  useEffect(() => {
    const validation = validateReportDateRange(dateFrom, dateTo);

    if (!validation.ok) {
      return;
    }

    if (
      validation.dateFrom === listParams.dateFrom &&
      validation.dateTo === listParams.dateTo
    ) {
      return;
    }

    const timeout = window.setTimeout(() => {
      const query = buildMonthReportSearchParams({
        dateFrom: validation.dateFrom,
        dateTo: validation.dateTo,
      });

      if (mode === 'new') {
        router.replace(`/report/new${query}`);
        return;
      }

      if (reportId) {
        router.replace(`/reports/${reportId}${query}`);
      }
    }, DEBOUNCE_MS);

    return () => window.clearTimeout(timeout);
  }, [
    dateFrom,
    dateTo,
    listParams.dateFrom,
    listParams.dateTo,
    mode,
    reportId,
    router,
  ]);

  function handleSaveConfirm() {
    if (!resolvedDates) {
      return;
    }

    const nameError = validateReportName(title);

    if (nameError) {
      setSaveError(nameError);
      return;
    }

    setSaveError(null);

    startTransition(async () => {
      const input = {
        name: title,
        dateFrom: resolvedDates.dateFrom,
        dateTo: resolvedDates.dateTo,
      };

      const result =
        mode === 'new'
          ? await createReport(input)
          : reportId
            ? await updateReport(reportId, input)
            : { ok: false as const, error: 'Report not found.' };

      if (!result.ok) {
        setSaveError(result.error);
        return;
      }

      setSaveDialogOpen(false);

      if (mode === 'new') {
        router.push('/reports');
        return;
      }

      setSaveSuccess('Report saved.');
      router.refresh();
    });
  }

  return (
    <div className="flex flex-col gap-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <ReportTitleInput
          value={title}
          onChange={handleTitleChange}
          disabled={isPending}
          className="min-w-[200px] flex-1"
        />
        <div className="flex shrink-0 flex-wrap items-center gap-2">
          <Button
            type="button"
            disabled={!canSave || isPending}
            onClick={() => {
              setSaveError(null);
              setSaveDialogOpen(true);
            }}
          >
            Save
          </Button>
          <Button type="button" variant="ghost" asChild>
            <Link href="/reports">Back to reports</Link>
          </Button>
        </div>
      </div>

      <div className="flex flex-wrap items-end gap-3">
        <Field className="w-full sm:w-auto">
          <FieldLabel htmlFor="report-date-range">Date range</FieldLabel>
          <DateRangePicker
            id="report-date-range"
            value={{ dateFrom, dateTo }}
            onValueChange={({ dateFrom: nextFrom, dateTo: nextTo }) => {
              handleDateRangeChange(nextFrom, nextTo);
            }}
          />
        </Field>
      </div>

      {validationError ? (
        <p className="text-sm text-destructive" role="alert">
          {validationError}
        </p>
      ) : null}

      {showSaveSuccess ? (
        <p className="text-sm text-muted-foreground" role="status">
          {saveSuccess}
        </p>
      ) : null}

      {showDashboard && groupedTotals ? (
        <section className="flex flex-col gap-6">
          <div>
            <h2 className="text-lg font-semibold">By category</h2>
            <p className="text-sm text-muted-foreground">
              Totals for transactions between {listParams.dateFrom} and{' '}
              {listParams.dateTo}
            </p>
          </div>
          {!hasTotals ? (
            <Empty className="border">
              <EmptyHeader>
                <EmptyTitle>No transactions in range</EmptyTitle>
                <EmptyDescription>
                  Try a different date range.
                </EmptyDescription>
              </EmptyHeader>
            </Empty>
          ) : (
            <>
              {monthReportCategoryTableTypes.map((tableType) => (
                <MonthReportCategoryTotalsTable
                  key={tableType}
                  tableType={tableType}
                  data={groupedTotals[tableType]}
                  dateFrom={listParams.dateFrom}
                  dateTo={listParams.dateTo}
                  categories={categories}
                />
              ))}
            </>
          )}
        </section>
      ) : null}

      <SaveReportDialog
        open={saveDialogOpen}
        onOpenChange={setSaveDialogOpen}
        name={title.trim()}
        dateFrom={resolvedDates?.dateFrom ?? dateFrom}
        dateTo={resolvedDates?.dateTo ?? dateTo}
        isPending={isPending}
        error={saveError}
        onConfirm={handleSaveConfirm}
      />
    </div>
  );
}

export { NEW_REPORT_TITLE };
